name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Unit Testing & Code Coverage
        run: mvn clean test jacoco:report

      - name: Build and Package JAR
        run: mvn package -DskipTests

      - name: Build and Tag Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: bhargava895/githubactions:latest

      - name: Scan Docker Image with Trivy
        run: |
          docker run --rm -v $(pwd):/src -w /src aquasec/trivy bhargava895/githubactions:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: bhargava895/githubactions:latest
